### PR TITLE
Add dnstools

### PR DESCRIPTION
**Pull request by indyfree**
Towards https://github.com/giantswarm/giantswarm/issues/1902

We need some dns tools to test https://github.com/giantswarm/kubernetes-coredns.

Also took the chance to update to latest alpine version.

### CODE REVIEW

**Review by xh3b4sd — COMMENTED** [review]
@giantswarm/sre might want to chime in here. I cannot say anything useful here.

**Comment by indyfree** [comment]
This is just a tool container we use for helm testing, and we need some additional dns cli utils, like `host` therefore. Don't know if sres have seen it. 

See e.g. here  https://github.com/giantswarm/kubernetes-nginx-ingress-controller/blob/master/helm/kubernetes-nginx-ingress-controller-chart/templates/test/tests.yaml#L7

**Review by fgimenez — APPROVED** [review]
LGTM

**Comment by xh3b4sd** [comment]
Well yes, but maybe there is already something like this used by the SREs. Maybe there is a vision for these things and before everybody does something different I just thought some communication or rethinking would be good before we do something we have to refactor like mad later on again.

**Comment by indyfree** [comment]
Yes your right, having visibility and thinking is good. IMO we could have some kind of catalogue of custom curated "utility" containers, that are used in production. And only use these, so not everybody creates own images. 

E.g. there's this: https://github.com/giantswarm/alpine-curl and it's pretty hard to find out, when and where we (still?) use it.

**Pull request merged**
